import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "react-query";

const Home: NextPage = () => {
	const { data } = useQuery("hello", () => axios.get("/api/hello"));
	console.log(data);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</div>
	);
};

export default Home;
